package ro.cookbook.util;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;
import ro.cookbook.domain.Recipe;
import ro.cookbook.domain.User;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Objects;

@Component
public class PdfExportHelper {

    public void createPdf(Recipe recipe, User user) {
        Document document = new Document();
        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(recipe.getRecipeName() + ".pdf"));
            document.open();
            if (!Objects.isNull(user)) {
                document.add(new Paragraph("Recipe generated by " + user.getFirstName()
                        + "from www.cookbook.ro" + " on: " +
                        getCurrentDate()));
            } else {
                document.add(new Paragraph("Recipe generated from www.cookbook.ro" + " on: " +
                        getCurrentDate()));
            }

            document.add(new Paragraph(recipe.getRecipeName()));
            document.close();
            writer.close();
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
        }

    }

    private String getCurrentDate() {
        return new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
    }

}
