package ro.cookbook.util;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;
import ro.cookbook.domain.Recipe;
import ro.cookbook.domain.User;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Objects;

@Component
public class PdfExportHelper {

    public ByteArrayInputStream createPdf(Recipe recipe, User user) {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(document, out);
            document.open();
            if (!Objects.isNull(user)) {
                document.add(new Paragraph("Recipe generated by " + user.getFirstName()
                        + "from www.cookbook.ro" + " on: " +
                        getCurrentDate()));
            } else {
                document.add(new Paragraph("Recipe generated from www.cookbook.ro" + " on: " +
                        getCurrentDate()));
            }
            document.add(new Paragraph(recipe.getRecipeName()));
            document.close();

        } catch (DocumentException e) {
            e.printStackTrace();
        }
        return new ByteArrayInputStream(out.toByteArray());
    }

    private String getCurrentDate() {
        return new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
    }

}
